#!/usr/bin/env bash
# installing and config load balancer
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 29535-web-01 54.173.9.236:80 check
    server 29535-web-02 3.85.16.137:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
