#!/usr/bin/env bash
# Script that installs and configures HAproxy load balancer on my lb-01 server 

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy=2.5.\*
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 29535-web-02 34.239.253.247:80 check\n\tserver 29535-lb-01 52.3.251.78:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
